import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './componets/navbar/Navbar';

export const metadata = {
  title: 'xin chao chichi',
  description: 'Generated by create next app',
}

const font = Inter({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
